package com.example.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Login : Screen("login")
    object Register : Screen("register")
    object ForgotPassword : Screen("forgot_password")
    object Home : Screen("home")
    object History : Screen("history")
    object Goal : Screen("goal")
    object Progress : Screen("progress")
    object AICoach : Screen("ai_coach")
    object Profile : Screen("profile")
    object FoodAnalysis : Screen("food_analysis")
    object FoodAnalysisResult : Screen("food_analysis_result")
    object FoodAnalysisHistory : Screen("food_analysis_history")
    object AiProcessing : Screen("ai_processing")
    object EodProcessing : Screen("eod_processing")
    object DailyNutritionReport : Screen("daily_nutrition_report")
    object DailyAiVideo : Screen("daily_ai_video")
    object LegalPrivacy : Screen("legal_privacy")
    object TermsConditions : Screen("terms_conditions")
    object PrivacyPolicy : Screen("privacy_policy")
    object HealthDisclaimer : Screen("health_disclaimer")
    object AiConsent : Screen("ai_consent")
    object DataPrivacy : Screen("data_privacy")
    object DeleteAccount : Screen("delete_account")
    object HelpSupport : Screen("help_support")
    object AboutApp : Screen("about_app")
    object Premium : Screen("premium")
    object PermNotification : Screen("perm_notification")
    object PermCamera : Screen("perm_camera")
    object PermMicrophone : Screen("perm_microphone")
    object PermPhotos : Screen("perm_photos")
}
